### ISSUE TITLE
Run all tests on CI

### ISSUE THREAD

**Issue by craigtaub** [mochajs/mocha-examples#14]
The best way to check that the code still works.

**Comment by craigtaub** [comment]
Possibly make a monorepo so its easier to have consistent standards.

**Comment by wnghdcjfe** [comment]
Is it OK to use Travis? Do you have anything else in mind?

**Comment by craigtaub** [comment]
Travis + lerna.

**Comment by craigtaub** [comment]
Closing as this is now done
