### ISSUE TITLE
Suggestions for the future

### ISSUE THREAD

**Issue by craigtaub** [mochajs/mocha-examples#2]
Leave a comment if you have a request or suggestion for a configuration you think would be useful.

See https://github.com/mochajs/mocha-examples#potential-setups-to-add-in-future for examples.

**Comment by craigtaub** [comment]
Think i'll start this with one which gets requests alot.

- **Pass user defined values from a test to a Reporter**

**Comment by craigtaub** [comment]
Rest API is definitely one we need.

**Comment by lookfirst** [comment]
`.mocharc.ts`

**Comment by wnghdcjfe** [comment]
gogogo

**Comment by wnghdcjfe** [comment]
vue -webpack

**Comment by leehwarang** [comment]
@craigtaub 

Hi, I'd like to suggest `react-hooks-example` as a new feature. There are a lot of React projects made using hooks, and I don't think we can easily find a way to write test codes for them. Let me know what you think.

**Comment by craigtaub** [comment]
@leehwarang this might be more a question around "how to use Hooks" rather than "how to use Mocha". Their [recipes](https://reactjs.org/docs/testing-recipes.html#act) are pretty good.

But saying that I like the idea. Just feel a new app is overkill (as we already have the [react](https://github.com/mochajs/mocha-examples/tree/master/react-webpack) example). Perhaps lets add it there.

**Comment by seohyun0120** [comment]
Hi @craigtaub 
I'd like to suggest `Typescript and Babel combination`. I saw this one listed at `Potential setups to add in future`. I think `Typescript` and `Babel` examples are pretty good. So I would like to combine them. Let me know if it's okay for me to start this project. :)

**Comment by craigtaub** [comment]
@seohyun0120 Feel free to give it a go and pls try to follow similar architecture/practices as the babel example. Thanks so much we really appreciate any help we can get with these.

**Comment by wnghdcjfe** [comment]
I think puppeteer example is needed

**Comment by HyunSangHan** [comment]
@craigtaub 
I created PR #27 about `async setup with --delay`. I'll wait for your review. :)

**Comment by dschinkel** [comment]
I'm pretty much ditching mocha at this point unfortunately due to lack of support for TS and easy configuration thereof.  I can't get mocha to work with TS.  I hate to have to use Jest as it's slow but I may not have a choice if it makes it easier to config with my React Enzyme tests

**Comment by craigtaub** [comment]
@dschinkel we have examples on react/webpack/[typescript/babel](https://github.com/mochajs/mocha-examples/tree/master/packages/typescript-babel) etc have you seen/tried them?

**Comment by dschinkel** [comment]
No I do not setup my project this way nor do I want to..it's bizarre and not common.  That's my entire point.  It's some frankenstein way to do so compared to what and how much you should have to do just to get this working with mocha.  I am using ts-node like everyone else out there.

**Comment by Munter** [comment]
Hi @dschinkel 

I think you should consider the tone you are using towards people who spend their valuable spare time on maintaining a piece of central infrastructure you clearly rely on.

The problem with your setup is that typescript/tsx code is actually quite hard to just run out of the box in node. Notice how I don't mention mocha in this sentence. You need to get your stuff to work in node, and then mocha will work. I do agree that we are missing an example of a setup that resembles yours, but to be honest my interest in spending time on your case just diminished quite a bit by witnessing your assumes priviledge.

How about you meet us half way and start actually giving some constructive feedback on the missing setup, for example by starting a PR with an example setup, even one showing errors. Then we have an actual test case we can work on fixing

**Comment by dschinkel** [comment]
It's not my tone, I'm being straight up telling you why I don't want to use that.

**Comment by JoshuaKGoldberg** [comment]
It's been over 4 years since activity on this issue. If anybody still wants any of the examples that don't yet exist, please do file a new issue explaining why in detail. Cheers! ☕
