### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by visortelle** [mochajs/mocha-examples#23]
<img width="471" alt="Screen Shot 2019-12-27 at 10 08 06 PM" src="https://user-images.githubusercontent.com/9302460/71529381-7861df00-28f5-11ea-8dfc-9b97f34b8ce6.png">

`=>` https://github.com/mochajs/mocha-examples/tree/master/typescript `=` `GitHub 404`

The link should be:

https://github.com/mochajs/mocha-examples/blob/master/packages/typescript

**Comment by craigtaub** [comment]
This is now fixed and released in mocha v7 via https://github.com/mochajs/mocha/pull/4129
