### ISSUE TITLE
How to pass variables from a --file setup to all the tests?

### ISSUE THREAD

**Issue by lolpez** [mochajs/mocha-examples#25]
In this [example](https://github.com/mochajs/mocha-examples/tree/master/packages/async-setup-with-file) there is a before and after hooks in a separated file using the Mocha --file command.
How can I create variables inside those hooks and to be accessible in other tests? For example:

`prepare.js`

```Javascript
before(function() {
    this.myVariable = 123;
});
```

`myTest.spec.js`

```Javascript
describe('Just a simple test', function () {
  it('Verifies the myVariable variable', async () => {
    expect(this.myVariable).to.eq(123); //should pass
  });
});
```

**Comment by craigtaub** [comment]
As far as im aware the only way to do this is either:
1. via an environment variable
2. setting value as a `global`

**Comment by lolpez** [comment]
Are you sure using `global` is a good idea?

**Comment by outsideris** [comment]
Use `function` instead arrow function in `myTest.spec.js`. 
You can access `this.myVariable` in test cases.

**Comment by lolpez** [comment]
Thanks, it works! Also, is there a way to make it work using async functions?

**Comment by lolpez** [comment]
oh nvm I just had to add the async keyword in the hook without using arrow functions
```javascript
before(async function() {
    this.myVariable = 123;
});
```
Thanks buddy!

**Comment by craigtaub** [comment]
Nice
