### ISSUE TITLE
typescript with ts-node and ESM support

### ISSUE THREAD

**Issue by juergba** [mochajs/mocha-examples#47]
Add a **typescript** sample using _ts-node_ and node's native ESM support.
Note: _ts-node_ uses Node's loader-hooks which are still experimental.

You can find info: [ts-node/1007](https://github.com/TypeStrong/ts-node/issues/1007)
and a working sample: [ts-node/discussion](https://github.com/TypeStrong/ts-node/discussions/1268)

**Comment by cspotcode** [comment]
Thanks.  Time permitting I'll send a pull request with a sample.  Till then, I'm subscribed to this thread and can answer questions.

**Comment by Dunky13** [comment]
I'm looking for a solution on this as well

**Comment by PabloSzx** [comment]
All I get trying to use TypeScript with ESM is: 
![image](https://user-images.githubusercontent.com/8672915/136700716-b993e2e2-9319-4aa6-ae3c-c25ecf106be5.png)

there isn't any workaround?

**Comment by PabloSzx** [comment]
> there isn't any workaround?

I found a workaround myself, modify the line 44 of [mocha/lib/nodejs/esm-utils.js](https://github.com/mochajs/mocha/blob/master/lib/nodejs/esm-utils.js#L44) with the logic you want for it to load the test files with `import()`, a simple `if (true)` will be enough.

You can either use [patch-package](https://github.com/ds300/patch-package) (__which is not being maintained anymore, so be aware__) or simply with a custom `postinstall` script using `writeFileSync` like this:

```json
{
  "postinstall": "node patch.cjs"
}
```

```js
// patch.cjs
const { writeFileSync, readFileSync } = require("fs");

const mochaEsmUtilsPath = require.resolve("mocha/lib/nodejs/esm-utils.js");
writeFileSync(
  mochaEsmUtilsPath,
  readFileSync(mochaEsmUtilsPath, { encoding: "utf-8" }).replace(
    "path.extname(file) === '.mjs'",
    "true"
  ),
  {
    encoding: "utf-8",
  }
);
```

**Comment by fcamblor** [comment]
Thanks to all of you here, it helped me a lot :-)

I would simply add that one requirement is to use `mocha@9` (`mocha@9.1.3` for me) as I was on `mocha@8` and I was getting following error : 
```TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"```

**Comment by FauxFaux** [comment]
Hi everyone else from search results.

This only works on node 16, haven't been able to get it to work on 18 or 20.

**Comment by sahin52** [comment]
I'm unable to find an example like this:
chai latest version: 5.xx
mocha latest version: 10.xx
and package.json type is not module.

I can't import from chai:  
`import { expect, assert } from 'chai'; `
I'm getting:   
`TypeError: Unknown file extension ".ts"`
for the command:  
`mocha -r ts-node/register -r ts-node/esm src/tests/**/*.ts` if I have 
`"type": "module"` in package.json. If I remove this, I'm getting weird typescript errors which don't exist:

```
Exception during run: src/tests/utils/misc.ts:166:32 - error TS2339: Property 'property11' does not exist on type '{}'.

166         (0, chai_1.expect)(obj.property11.p.b.c).to.equal(2);
                                   ~~~~~~~~~~
src/tests/utils/misc.ts:245:46 - error TS7006: Parameter 'x' implicitly has an 'any' type.

245         var compareStringsLength = function (x, y) {
                                                 ~
src/tests/utils/misc.ts:245:49 - error TS7006: Parameter 'y' implicitly has an 'any' type.

245         var compareStringsLength = function (x, y) {
```

**Comment by JoshuaKGoldberg** [comment]
This was done in #76. ✅ 

If anybody wants more TypeScript info, and there isn't an existing issue (e.g. #40) filed, please do file a new issue explaining why. Cheers! ☕

**Comment by 1mike12** [comment]
> This only works on node 16, ~haven't been able to get it to work on 18 or 20~.
> 
> Newer nodes don't like, and don't need(?) the `"experimental-specifier-resolution=node",`

This has not been my experience. I want to get rid of the warnings as much as anyone. But on node 18, 20, and 22, removing that line will get

```
 Exception during run: Error: Cannot find module '/Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/example' imported from /Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/example.test.ts
    at finalizeResolution (/Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (/Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/node_modules/ts-node/src/esm.ts:168:34)
    at /Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/Users/mike/ExampleProjects/mocha-typescript-investigation/esm_ts-node/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)

```
