### ISSUE TITLE
Mocha : programmatic-usage, How can we implement babel/other compilations?

### ISSUE THREAD

**Issue by neghani** [mochajs/mocha-examples#8]
Mocha : programmatic-usage, How can we implement babel/other compilations?

**Comment by craigtaub** [comment]
@neghani 

1. You need a babel config file defined ([see our example](https://github.com/mochajs/mocha-examples/blob/master/babel/babel.config.js))

2. Inside the file which runs mocha (e.g. [run_mocha.js](https://github.com/mochajs/mocha-examples/blob/master/programmatic-usage/tests/run_mocha.js)) require the babel hook.

So this:
```
const fs = require('fs');
const path = require('path');
const Mocha = require('mocha');

// Instantiate a Mocha with options
const mocha = new Mocha({
  reporter: 'list',
});
```

Becomes
```
const fs = require('fs');
const path = require('path');
const Mocha = require('mocha');
require("@babel/register");

// Instantiate a Mocha with options
const mocha = new Mocha({
  reporter: 'list',
});
```

Hopefully that will work for you. Please let me know.

**Comment by craigtaub** [comment]
@neghani has there been any movement on this? Will close if do not hear back soon.

**Comment by craigtaub** [comment]
Closing as seems nothing outstanding.

**Comment by neghani** [comment]
Hi Craig, thanks for helping i found the appropriate documentation later and I was away for a while to respond thanks for closing.
